<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DeshmukH" failures="1" tests="7" name="Test" time="0.297" errors="0" timestamp="2022-03-10T09:42:29 IST">
  <testcase classname="TestNg_Suite._1_FirstTest" name="setup" time="0.016"/>
  <testcase classname="TestNg_Suite._1_FirstTest" name="setup" time="0.003"/>
  <testcase classname="TestNg_Suite._1_FirstTest" name="setup" time="0.011"/>
  <testcase classname="TestNg_Suite._1_FirstTest" name="setup" time="0.007"/>
  <testcase classname="TestNg_Suite._2_SecondTest" name="demo" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNg_Suite._2_SecondTest.demo(_2_SecondTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="TestNg_Suite._3_ThirdTest" name="meth2" time="0.009"/>
  <testcase classname="TestNg_Suite._3_ThirdTest" name="meth1" time="0.004"/>
  <testcase classname="TestNg_Suite._2_SecondTest" name="dems" time="0.0">
    <ignored/>
  </testcase> <!-- dems -->
  <testcase classname="TestNg_Suite._3_ThirdTest" name="meth3" time="0.0">
    <ignored/>
  </testcase> <!-- meth3 -->
</testsuite> <!-- Test -->
